### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Finneyyy** [tmedwards/CoCEd#11]
[CoCEd: 1.3.0.42598, CoC Data: 0.9.4]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.ItemSlotVM.get_Type() in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\ItemVM.cs:line 109
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, Boolean isRevampMod) in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 166
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in C:\Users\tmedwards\Documents\Visual Studio 2015\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 125
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

What do I do?

**Comment by tmedwards** [comment]
Post the save file somewhere, so I can analyze it.
