### ISSUE TITLE
Error that causing CoCEd to chrash

### ISSUE THREAD

**Issue by Kitata** [tmedwards/CoCEd#29]
Here is the error code I'm getting:

[CoCEd: 1.3.1.28497, CoC Data: 1.0.2_mod_1.4.17]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.GameVM.UpdateChest()
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, Boolean isRevampMod)
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kitteh6660** [comment]
I was able to identify the cause and got a pull request waiting: https://github.com/tmedwards/CoCEd/pull/27

**Comment by tmedwards** [comment]
See if the [latest release (v1.3.2)](https://github.com/tmedwards/CoCEd/releases/latest) resolves the issue.

**Comment by Kitata** [comment]
It works now!

**Comment by tmedwards** [comment]
I'm glad.
