### ISSUE TITLE
Application quits when attempting to open save file

### ISSUE THREAD

**Issue by fastrack625** [tmedwards/CoCEd#3]
[CoCEd: 1.2.18.4312]
System.UnauthorizedAccessException: Access to the path '635607094366576061.bak' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CoCEd.Model.FileManager.CreateBackup(String sourcePath) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\Model\FileManager.cs:line 362
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 117
   at CoCEd.ViewModel.ImportRootVM.OnClick() in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\FilesVM.cs:line 257
   at CoCEd.View.TopBar.menu_Click(Object sender, RoutedEventArgs e) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\View\TopBar.xaml.cs:line 135
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
> ***Access to the path*** *'635607094366576061.bak'* ***is denied.***

Try opening your local app data directory (Run [Win+R] or search for: `%LocalAppData%`) and deleting the `CoCEd` directory.

**Comment by tmedwards** [comment]
Closing due to inactivity.
