### ISSUE TITLE
Unable to open CoCED v1.3.2

### ISSUE THREAD

**Issue by Mossmin** [tmedwards/CoCEd#30]
Says that it can't find CoCED.DataXianxia.xml file and I don't know where to find it or how to download it

**Comment by HollowOO12** [comment]
I have the same problem too.  Tried a work around by making it with an old version on github now I get this.

[CoCEd: 1.3.2.15146]
System.InvalidOperationException: There is an error in XML document (2, 3). ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 2, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParsePI(StringBuilder piInDtdStringBuilder)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderXmlDataSet.Read11_CoCEd()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at CoCEd.Model.XmlData.LoadXml(String xmlFile) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\Model\XmlData.cs:line 50
   at CoCEd.App.Initialize() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\App.xaml.cs:line 85
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
The [latest release (v1.3.3)](https://github.com/tmedwards/CoCEd/releases/latest) should fix the Xianxia issue.  See what that does for you.
