### ISSUE TITLE
Fixed the Xianxia thing, only for this to happen

### ISSUE THREAD

**Issue by TitanMilo** [tmedwards/CoCEd#31]
So i managed to find a Xianxia file to download, but now I get this error:

[CoCEd: 1.3.2.15146]
System.InvalidOperationException: There is an error in XML document (8, 2). ---> System.InvalidOperationException: <html xmlns=''> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderXmlDataSet.Read11_CoCEd()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at CoCEd.Model.XmlData.LoadXml(String xmlFile) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\Model\XmlData.cs:line 50
   at CoCEd.App.Initialize() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\App.xaml.cs:line 85
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
The [latest release (v1.3.3)](https://github.com/tmedwards/CoCEd/releases/latest) should fix the Xianxia issue.  See what that does for you.

**Comment by TitanMilo** [comment]
that did it
