### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShadowFoxXx13** [tmedwards/CoCEd#33]
[CoCEd: 1.2.17.23877, CoC Data: 1.0.2_mod_1.4.17c]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.GameVM.UpdateChest() in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 214
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, Boolean isRevampMod) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 135
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 125
   at CoCEd.ViewModel.FileVM.OnClick() in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\FilesVM.cs:line 425
   at CoCEd.View.TopBar.subMenu_Click(Object sender, RoutedEventArgs e) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\View\TopBar.xaml.cs:line 124
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ambjoorn94** [comment]
The problem may be that your CoCEd is outdated while your revamp mod is not.

**Comment by tmedwards** [comment]
That is indeed the problem.  You need to update your CoCEd version.
