### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zerixton** [tmedwards/CoCEd#34]
[CoCEd: 1.3.3.223, CoC Data: 1.0.2_mod_1.4.16d]
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoCEd.ViewModel.GameVM.GetItemStorageObj() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 252
   at CoCEd.ViewModel.GameVM.UpdateChest() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.Core.cs:line 257
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, ModType modType) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 144
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 151
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
CoCEd was updated to support CoC-Revamp-Mod v1.4.17.  You're clearly using an earlier version there, so try updating to CoC-Revamp-Mod ≥v1.4.17.
