### ISSUE TITLE
Importing saves causes a crash

### ISSUE THREAD

**Issue by Ninetales10** [tmedwards/CoCEd#39]
[CoCEd: 1.3.3.223]
System.NotImplementedException: Unknown endianness
   at CoCEd.Model.AmfReader.ReadStandardFile(AmfFile file, String& name) in c:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\Model\AmfReader.cs:line 51
   at CoCEd.Model.AmfReader.Run(AmfFile file, String& name, SerializationFormat& format) in c:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\Model\AmfReader.cs:line 35
   at CoCEd.Model.AmfFile..ctor(String path) in c:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\Model\AmfFile.cs:line 36

__________________________________________________________________________________________________
after i tried to load the save anyway, it crashed and i got the error message below.

[CoCEd: 1.3.3.223]
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at CoCEd.ViewModel.ArrayVM`1..ctor(AmfObject obj, Func`2 selector) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 305
   at CoCEd.ViewModel.CockArrayVM..ctor(GameVM game, AmfObject obj) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\CockVM.cs:line 13
   at CoCEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM, ModType modType) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\GameVM.cs:line 74
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 151
   at CoCEd.ViewModel.FileVM.OnClick() in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\ViewModel\FilesVM.cs:line 446
   at CoCEd.View.TopBar.subMenu_Click(Object sender, RoutedEventArgs e) in C:\Users\tmedwards\Documents\Visual Studio 2017\Projects\CoCEd\CoCEd\View\TopBar.xaml.cs:line 126
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

__________________________________________________________________________________________________

Here are the files in question.

[CoCEd.zip](https://github.com/tmedwards/CoCEd/files/5071538/CoCEd.zip)

**Comment by Ninetales10** [comment]
oh, and here's the files i tried (i couldn't put them separately, so they're zipped)
[CoCEd.zip](https://github.com/tmedwards/CoCEd/files/5071532/CoCEd.zip)
