### ISSUE TITLE
Save Editor for Android files.

### ISSUE THREAD

**Issue by Armatas** [tmedwards/CoCEd#6]
I saved my current game into a file, then located it under the android data and it loads in strangely into the editor giving me a crash error. I can find it under backups and it gives me a message that the the file is loading like a slot when it's a file? Either way, when I try to save it back to the same format it doesn't allow me to load from the file at all inside the app and it doesn't seem to see it as a soc file. I can't seem to locate the data inside the phone for the soc files either. I'd appreciate some guidance on this.

Here's the error message:

[CoCEd: 1.2.20.21197]
System.UnauthorizedAccessException: Access to the path '635856858299849136.bak' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at CoCEd.Model.FileManager.TryDeleteIdenticalFile(String sourcePath, FileInfo[] existingFiles) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\Model\FileManager.cs:line 386
   at CoCEd.Model.FileManager.CreateBackup(String sourcePath) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\Model\FileManager.cs:line 358
   at CoCEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup) in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\VM.cs:line 118
   at CoCEd.ViewModel.ImportRootVM.OnClick() in c:\Users\tmedwards\Documents\Visual Studio 2013\Projects\CoCEd\CoCEd\ViewModel\FilesVM.cs:line 255
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by tmedwards** [comment]
I don't use the mobile builds of CoC, so I can't offer any general advice.  Try the [official CoC forums](https://fenoxo.com/forum/index.php?/forum/12-coc/ "https://fenoxo.com/forum/index.php?/forum/12-coc/") (and no, I don't mean the CoCEd thread there).  And if this was the CoC-Revamp-Mod, use its thread specifically—the mods get grumpy when you don't.


The "File format different from expected format" message is just what it says.  CoC has two different, and incompatible, save file types: "Slot" format saves (a.k.a. those created via the "Save" button) and "Save to File" format saves (a.k.a. those created by the "Save to File" button).  Attempting to load a "Slot" save as though it were a "Save to File" save, or vice versa, will cause CoC to think the save is corrupt, at best, or see the save deleted, at worse.  CoCEd's import dialog (Open > Import…) allows you to specify the format type of the save file you're trying to load—the export dialog (Save As > Export…) is similar.  Based on the warning you said you received, I'm assuming you tried to load a "Save to File" save without selecting that format (the default is "Slot" format).

That shouldn't have caused a crash, however, just the warning, so I'm unsure what to say.  If the version of CoC you're using is not the latest, then that may be the cause—CoCEd only supports the latest version of CoC (and CoC-Revamp-Mod).  Also, as a suggestion, don't try to edit the file directly on the mobile device.  Move it onto your computer, load it into CoCEd and edit it there, export it in the proper format, then move it back to your device.

**Comment by tmedwards** [comment]
Closing due to inactivity.
